[2025-03-27T16:05:33.007+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:05:33.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:05:33.011+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:05:33.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:05:33.967+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:05:34.057+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:05:34.056+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:05:34.266+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:05:34.266+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:00:00+00:00, run_after=2025-03-27 16:05:00+00:00
[2025-03-27T16:05:34.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.282 seconds
[2025-03-27T16:06:04.549+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:06:04.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:06:04.551+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:06:04.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:06:05.014+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:06:05.033+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:06:05.032+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:06:05.050+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:06:05.050+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:00:00+00:00, run_after=2025-03-27 16:05:00+00:00
[2025-03-27T16:06:05.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.521 seconds
[2025-03-27T16:06:35.125+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:06:35.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:06:35.127+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:06:35.127+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:06:35.539+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:06:35.722+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:06:35.722+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:06:35.737+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:06:35.737+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:00:00+00:00, run_after=2025-03-27 16:05:00+00:00
[2025-03-27T16:06:35.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.638 seconds
[2025-03-27T16:07:05.873+0000] {processor.py:186} INFO - Started process (PID=285) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:07:05.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:07:05.876+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:07:05.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:07:06.430+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:07:06.635+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:07:06.634+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:07:06.653+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:07:06.652+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:00:00+00:00, run_after=2025-03-27 16:05:00+00:00
[2025-03-27T16:07:06.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.801 seconds
[2025-03-27T16:07:37.045+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:07:37.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:07:37.048+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:07:37.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:07:37.778+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:07:37.985+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:07:37.984+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:07:38.003+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:07:38.003+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:00:00+00:00, run_after=2025-03-27 16:05:00+00:00
[2025-03-27T16:07:38.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.978 seconds
[2025-03-27T16:08:55.353+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:08:55.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:08:55.357+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:08:55.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:08:55.795+0000] {logging_mixin.py:190} WARNING - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[2025-03-27T16:09:55.819+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:09:55.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:09:55.826+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:09:55.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:09:56.288+0000] {logging_mixin.py:190} WARNING - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[2025-03-27T16:09:57.668+0000] {logging_mixin.py:190} INFO - Collecting scikit-learn
[2025-03-27T16:09:57.914+0000] {logging_mixin.py:190} INFO -   Downloading scikit_learn-1.6.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2025-03-27T16:09:57.949+0000] {logging_mixin.py:190} INFO - Requirement already satisfied: numpy>=1.19.5 in /home/airflow/.local/lib/python3.12/site-packages (from scikit-learn) (1.26.4)
[2025-03-27T16:09:58.110+0000] {logging_mixin.py:190} INFO - Collecting scipy>=1.6.0 (from scikit-learn)
[2025-03-27T16:09:58.158+0000] {logging_mixin.py:190} INFO -   Downloading scipy-1.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
[2025-03-27T16:09:58.295+0000] {logging_mixin.py:190} INFO - Collecting joblib>=1.2.0 (from scikit-learn)
[2025-03-27T16:09:58.341+0000] {logging_mixin.py:190} INFO -   Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2025-03-27T16:09:58.412+0000] {logging_mixin.py:190} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn)
[2025-03-27T16:09:58.460+0000] {logging_mixin.py:190} INFO -   Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
[2025-03-27T16:09:58.532+0000] {logging_mixin.py:190} INFO - Downloading scikit_learn-1.6.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
[2025-03-27T16:09:59.161+0000] {logging_mixin.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 22.9 MB/s eta 0:00:00
[2025-03-27T16:09:59.210+0000] {logging_mixin.py:190} INFO - Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
[2025-03-27T16:09:59.274+0000] {logging_mixin.py:190} INFO - Downloading scipy-1.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.3 MB)
[2025-03-27T16:10:01.658+0000] {logging_mixin.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 15.6 MB/s eta 0:00:00
[2025-03-27T16:10:01.709+0000] {logging_mixin.py:190} INFO - Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
[2025-03-27T16:10:02.723+0000] {logging_mixin.py:190} INFO - Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
[2025-03-27T16:10:08.529+0000] {logging_mixin.py:190} INFO - Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0
[2025-03-27T16:10:08.811+0000] {logging_mixin.py:190} WARNING - 
[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
[2025-03-27T16:10:09.369+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:10:09.387+0000] {logging_mixin.py:190} INFO - Sync 1 DAGs
[2025-03-27T16:10:09.401+0000] {logging_mixin.py:190} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:05:00+00:00, run_after=2025-03-27 16:10:00+00:00
[2025-03-27T16:10:09.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 13.627 seconds
[2025-03-27T16:10:39.622+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:10:39.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:10:39.625+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:10:39.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:10:40.146+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:10:40.163+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:10:40.162+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:10:40.357+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:10:40.357+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:05:00+00:00, run_after=2025-03-27 16:10:00+00:00
[2025-03-27T16:10:40.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.755 seconds
[2025-03-27T16:11:10.872+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:11:10.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:11:10.875+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:11:10.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:11:11.305+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:11:11.321+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:11:11.321+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:11:11.511+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:11:11.511+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:05:00+00:00, run_after=2025-03-27 16:10:00+00:00
[2025-03-27T16:11:11.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.667 seconds
[2025-03-27T16:11:42.234+0000] {processor.py:186} INFO - Started process (PID=363) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:11:42.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:11:42.237+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:11:42.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:11:42.840+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:11:42.855+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:11:42.855+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:11:43.043+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:11:43.043+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:05:00+00:00, run_after=2025-03-27 16:10:00+00:00
[2025-03-27T16:11:43.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.835 seconds
[2025-03-27T16:12:13.600+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:12:13.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:12:13.604+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:12:13.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:12:14.045+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:12:14.063+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:12:14.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:12:14.285+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:12:14.285+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:05:00+00:00, run_after=2025-03-27 16:10:00+00:00
[2025-03-27T16:12:14.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.714 seconds
[2025-03-27T16:12:44.351+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:12:44.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:12:44.355+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:12:44.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:12:45.268+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:12:45.284+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:12:45.284+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:12:45.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.973 seconds
[2025-03-27T16:13:15.517+0000] {processor.py:186} INFO - Started process (PID=588) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:13:15.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:13:15.520+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:13:15.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:13:16.204+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:13:16.217+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:13:16.217+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:13:16.232+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:13:16.232+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:10:00+00:00, run_after=2025-03-27 16:15:00+00:00
[2025-03-27T16:13:16.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.744 seconds
[2025-03-27T16:13:47.068+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:13:47.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:13:47.070+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:13:47.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:13:47.678+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:13:47.691+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:13:47.691+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:13:47.706+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:13:47.706+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:10:00+00:00, run_after=2025-03-27 16:15:00+00:00
[2025-03-27T16:13:47.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.667 seconds
[2025-03-27T16:14:17.881+0000] {processor.py:186} INFO - Started process (PID=738) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:14:17.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:14:17.885+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:14:17.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:14:18.594+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:14:18.612+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:14:18.612+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:14:18.630+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:14:18.630+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:10:00+00:00, run_after=2025-03-27 16:15:00+00:00
[2025-03-27T16:14:18.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.784 seconds
[2025-03-27T16:14:43.794+0000] {processor.py:186} INFO - Started process (PID=813) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:14:43.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:14:43.797+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:14:43.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:14:44.426+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:14:44.441+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:14:44.440+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:14:44.457+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:14:44.457+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:10:00+00:00, run_after=2025-03-27 16:15:00+00:00
[2025-03-27T16:14:44.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.684 seconds
[2025-03-27T16:15:14.683+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:15:14.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:15:14.686+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:15:14.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:15:15.315+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:15:15.329+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:15:15.329+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:15:15.345+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:15:15.344+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:15:15.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.680 seconds
[2025-03-27T16:15:45.805+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:15:45.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:15:45.808+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:15:45.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:15:46.588+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:15:46.601+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:15:46.601+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:15:46.617+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:15:46.617+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:15:46.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.831 seconds
[2025-03-27T16:16:16.698+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:16.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:16:16.701+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:16.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:17.557+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:17.576+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:17.575+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:16:17.597+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:17.597+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:16:17.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.922 seconds
[2025-03-27T16:16:48.161+0000] {processor.py:186} INFO - Started process (PID=1112) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:48.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:16:48.164+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:48.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:48.833+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:48.848+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:48.847+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:16:48.866+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:48.865+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:16:48.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.725 seconds
[2025-03-27T16:16:57.894+0000] {processor.py:186} INFO - Started process (PID=1131) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:57.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:16:57.897+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:57.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:58.688+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:16:58.709+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:58.709+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:16:58.734+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:16:58.734+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:16:58.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.877 seconds
[2025-03-27T16:17:29.264+0000] {processor.py:186} INFO - Started process (PID=1206) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:17:29.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:17:29.267+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:17:29.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:17:29.955+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:17:29.969+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:17:29.969+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:17:29.985+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:17:29.985+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:17:30.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.750 seconds
[2025-03-27T16:17:59.706+0000] {processor.py:186} INFO - Started process (PID=1281) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:17:59.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:17:59.710+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:17:59.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:18:00.457+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:18:00.472+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:18:00.472+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:18:00.490+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:18:00.490+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:18:00.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.816 seconds
[2025-03-27T16:18:30.854+0000] {processor.py:186} INFO - Started process (PID=1356) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:18:30.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:18:30.857+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:18:30.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:18:31.492+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:18:31.507+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:18:31.506+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:18:31.526+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:18:31.526+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:18:31.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.695 seconds
[2025-03-27T16:19:01.822+0000] {processor.py:186} INFO - Started process (PID=1431) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:19:01.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:19:01.825+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:19:01.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:19:02.824+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:19:02.837+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:19:02.837+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:19:02.853+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:19:02.853+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:19:02.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.050 seconds
[2025-03-27T16:19:33.370+0000] {processor.py:186} INFO - Started process (PID=1506) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:19:33.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:19:33.373+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:19:33.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:19:33.984+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:19:33.999+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:19:33.999+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:19:34.015+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:19:34.015+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:15:00+00:00, run_after=2025-03-27 16:20:00+00:00
[2025-03-27T16:19:34.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.666 seconds
[2025-03-27T16:20:04.310+0000] {processor.py:186} INFO - Started process (PID=1581) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:20:04.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:20:04.313+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:20:04.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:20:04.976+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:20:04.993+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:20:04.992+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:20:05.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.720 seconds
[2025-03-27T16:20:35.149+0000] {processor.py:186} INFO - Started process (PID=1660) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:20:35.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:20:35.152+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:20:35.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:20:35.958+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:20:35.973+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:20:35.973+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:20:35.988+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:20:35.988+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:20:00+00:00, run_after=2025-03-27 16:25:00+00:00
[2025-03-27T16:20:36.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.869 seconds
[2025-03-27T16:21:06.254+0000] {processor.py:186} INFO - Started process (PID=1735) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:21:06.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:21:06.257+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:21:06.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:21:06.951+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:21:06.965+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:21:06.965+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:21:06.979+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:21:06.979+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:20:00+00:00, run_after=2025-03-27 16:25:00+00:00
[2025-03-27T16:21:07.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.754 seconds
[2025-03-27T16:21:37.653+0000] {processor.py:186} INFO - Started process (PID=1813) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:21:37.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:21:37.656+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:21:37.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:21:38.334+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:21:38.348+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:21:38.348+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:21:38.363+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:21:38.363+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:20:00+00:00, run_after=2025-03-27 16:25:00+00:00
[2025-03-27T16:21:38.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.728 seconds
[2025-03-27T16:22:08.804+0000] {processor.py:186} INFO - Started process (PID=1888) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:22:08.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:22:08.807+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:22:08.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:22:09.431+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:22:09.446+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:22:09.446+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:22:09.463+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:22:09.462+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:20:00+00:00, run_after=2025-03-27 16:25:00+00:00
[2025-03-27T16:22:09.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.688 seconds
[2025-03-27T16:22:40.040+0000] {processor.py:186} INFO - Started process (PID=1963) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:22:40.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:22:40.044+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:22:40.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:22:43.342+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:22:43.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:22:43.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:22:43.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 3.335 seconds
[2025-03-27T16:23:13.548+0000] {processor.py:186} INFO - Started process (PID=2052) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:23:13.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:23:13.552+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:23:13.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:23:15.750+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:23:15.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:23:15.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:23:15.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.248 seconds
[2025-03-27T16:23:45.915+0000] {processor.py:186} INFO - Started process (PID=2129) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:23:45.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:23:45.918+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:23:45.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:23:48.215+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:23:48.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:23:48.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:23:48.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.338 seconds
[2025-03-27T16:24:18.522+0000] {processor.py:186} INFO - Started process (PID=2211) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:24:18.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:24:18.524+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:24:18.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:24:20.369+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:24:20.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:24:20.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:24:20.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.887 seconds
[2025-03-27T16:24:50.923+0000] {processor.py:186} INFO - Started process (PID=2286) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:24:50.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:24:50.925+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:24:50.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:24:57.753+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:24:57.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:24:57.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:24:57.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 6.871 seconds
[2025-03-27T16:25:27.970+0000] {processor.py:186} INFO - Started process (PID=2361) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:25:27.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:25:27.972+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:25:27.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:25:29.668+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:25:29.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:25:29.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:25:29.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.735 seconds
[2025-03-27T16:26:00.092+0000] {processor.py:186} INFO - Started process (PID=2442) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:26:00.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:26:00.094+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:26:00.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:26:01.612+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:26:01.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:26:01.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:26:01.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.558 seconds
[2025-03-27T16:26:32.279+0000] {processor.py:186} INFO - Started process (PID=2517) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:26:32.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:26:32.281+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:26:32.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:26:34.616+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:26:34.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:26:34.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:26:34.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.366 seconds
[2025-03-27T16:27:05.149+0000] {processor.py:186} INFO - Started process (PID=2592) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:27:05.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:27:05.151+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:27:05.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:27:06.984+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:27:06.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:27:06.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:27:07.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.872 seconds
[2025-03-27T16:27:37.293+0000] {processor.py:186} INFO - Started process (PID=2667) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:27:37.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:27:37.295+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:27:37.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:27:39.076+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:27:39.073+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:27:39.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:27:39.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.810 seconds
[2025-03-27T16:28:09.233+0000] {processor.py:186} INFO - Started process (PID=2742) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:28:09.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:28:09.235+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:28:09.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:28:12.832+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:28:12.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:28:12.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:28:12.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 3.640 seconds
[2025-03-27T16:28:43.028+0000] {processor.py:186} INFO - Started process (PID=2831) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:28:43.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:28:43.030+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:28:43.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:28:44.692+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:28:44.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:28:44.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:28:44.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.692 seconds
[2025-03-27T16:29:14.756+0000] {processor.py:186} INFO - Started process (PID=2913) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:29:14.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:29:14.757+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:29:14.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:29:16.819+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:29:16.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:29:16.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:29:16.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.090 seconds
[2025-03-27T16:29:47.423+0000] {processor.py:186} INFO - Started process (PID=2993) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:29:47.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:29:47.425+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:29:47.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:29:49.286+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:29:49.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:29:49.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:29:49.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.891 seconds
[2025-03-27T16:30:19.547+0000] {processor.py:186} INFO - Started process (PID=3084) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:30:19.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:30:19.549+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:30:19.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:30:21.388+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:30:21.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:30:21.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:30:21.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.878 seconds
[2025-03-27T16:30:52.322+0000] {processor.py:186} INFO - Started process (PID=3166) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:30:52.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:30:52.323+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:30:52.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:30:54.037+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:30:54.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:30:54.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:30:54.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.739 seconds
[2025-03-27T16:31:24.503+0000] {processor.py:186} INFO - Started process (PID=3242) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:31:24.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:31:24.505+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:31:24.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:31:26.242+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:31:26.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:31:26.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:31:26.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.777 seconds
[2025-03-27T16:31:57.243+0000] {processor.py:186} INFO - Started process (PID=3324) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:31:57.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:31:57.245+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:31:57.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:31:58.894+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:31:58.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:31:58.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:31:58.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.689 seconds
[2025-03-27T16:32:29.352+0000] {processor.py:186} INFO - Started process (PID=3405) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:32:29.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:32:29.355+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:32:29.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:32:31.124+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:32:31.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:32:31.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:32:31.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.813 seconds
[2025-03-27T16:33:01.561+0000] {processor.py:186} INFO - Started process (PID=3480) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:33:01.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:33:01.563+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:33:01.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:33:03.434+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:33:03.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:33:03.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:33:03.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.898 seconds
[2025-03-27T16:33:34.034+0000] {processor.py:186} INFO - Started process (PID=3555) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:33:34.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:33:34.037+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:33:34.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:33:35.883+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:33:35.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:33:35.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:33:35.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.886 seconds
[2025-03-27T16:34:06.177+0000] {processor.py:186} INFO - Started process (PID=3630) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:34:06.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:34:06.179+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:34:06.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:34:07.982+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:34:07.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:34:07.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:34:08.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.853 seconds
[2025-03-27T16:34:38.075+0000] {processor.py:186} INFO - Started process (PID=3705) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:34:38.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:34:38.077+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:34:38.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:34:39.974+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:34:39.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:34:39.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:34:39.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.926 seconds
[2025-03-27T16:35:10.240+0000] {processor.py:186} INFO - Started process (PID=3780) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:35:10.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:35:10.242+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:35:10.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:35:12.028+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:35:12.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:35:12.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:35:12.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.824 seconds
[2025-03-27T16:35:42.604+0000] {processor.py:186} INFO - Started process (PID=3855) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:35:42.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:35:42.606+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:35:42.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:35:45.738+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:35:45.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:35:45.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:35:45.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 3.160 seconds
[2025-03-27T16:36:15.819+0000] {processor.py:186} INFO - Started process (PID=3930) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:36:15.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:36:15.821+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:36:15.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:36:17.698+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:36:17.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:36:17.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:36:17.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.918 seconds
[2025-03-27T16:36:47.985+0000] {processor.py:186} INFO - Started process (PID=4005) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:36:47.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:36:47.987+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:36:47.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:36:49.872+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:36:49.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:36:49.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:36:49.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.929 seconds
[2025-03-27T16:37:19.977+0000] {processor.py:186} INFO - Started process (PID=4080) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:37:19.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:37:19.979+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:37:19.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:37:21.731+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:37:21.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:37:21.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:37:21.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.783 seconds
[2025-03-27T16:37:51.840+0000] {processor.py:186} INFO - Started process (PID=4156) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:37:51.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:37:51.843+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:37:51.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:37:53.783+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:37:53.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:37:53.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:37:53.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.974 seconds
[2025-03-27T16:38:23.852+0000] {processor.py:186} INFO - Started process (PID=4233) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:38:23.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:38:23.853+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:38:23.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:38:25.597+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:38:25.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:38:25.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:38:25.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.782 seconds
[2025-03-27T16:38:56.225+0000] {processor.py:186} INFO - Started process (PID=4312) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:38:56.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:38:56.227+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:38:56.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:38:58.485+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:38:58.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:38:58.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:38:58.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.288 seconds
[2025-03-27T16:39:29.431+0000] {processor.py:186} INFO - Started process (PID=4390) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:39:29.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:39:29.433+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:39:29.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:39:30.989+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:39:30.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:39:30.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:39:31.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.584 seconds
[2025-03-27T16:40:01.825+0000] {processor.py:186} INFO - Started process (PID=4483) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:40:01.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:40:01.827+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:40:01.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:40:03.635+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:40:03.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:40:03.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:40:03.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.836 seconds
[2025-03-27T16:40:34.332+0000] {processor.py:186} INFO - Started process (PID=4562) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:40:34.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:40:34.334+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:40:34.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:40:36.020+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:40:36.016+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:40:36.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:40:36.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.721 seconds
[2025-03-27T16:41:06.919+0000] {processor.py:186} INFO - Started process (PID=4642) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:41:06.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:41:06.921+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:41:06.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:41:08.531+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:41:08.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:41:08.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:41:08.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.651 seconds
[2025-03-27T16:41:39.155+0000] {processor.py:186} INFO - Started process (PID=4719) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:41:39.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:41:39.157+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:41:39.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:41:41.119+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:41:41.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:41:41.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:41:41.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.991 seconds
[2025-03-27T16:42:11.405+0000] {processor.py:186} INFO - Started process (PID=4794) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:11.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:42:11.407+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:42:11.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:13.156+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:42:13.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 116, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 86, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:42:13.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:13.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.784 seconds
[2025-03-27T16:42:18.269+0000] {processor.py:186} INFO - Started process (PID=4830) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:18.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:42:18.270+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:42:18.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:20.274+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:42:20.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 115, in <module>
    clear_data()
  File "/opt/airflow/dags/airflow_1.py", line 45, in clear_data
    df = pd.read_csv('https://github.com/Alexey3250/Start_ML/blob/main/Machine_learning/4_gradient_descend/hw/data.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2058, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 42, saw 39
[2025-03-27T16:42:20.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:20.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.038 seconds
[2025-03-27T16:42:51.136+0000] {processor.py:186} INFO - Started process (PID=4905) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:51.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:42:51.138+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:42:51.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:53.400+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:42:53.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 115, in <module>
    clear_data()
  File "/opt/airflow/dags/airflow_1.py", line 47, in clear_data
    df = df.drop('duration', axis=1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['duration'] not found in axis"
[2025-03-27T16:42:53.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:42:53.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 2.285 seconds
[2025-03-27T16:43:23.623+0000] {processor.py:186} INFO - Started process (PID=4980) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:43:23.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:43:23.625+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:43:23.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:43:24.717+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:43:24.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 115, in <module>
    clear_data()
  File "/opt/airflow/dags/airflow_1.py", line 47, in clear_data
    df = df.drop('duration', axis=1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['duration'] not found in axis"
[2025-03-27T16:43:24.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:43:24.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.126 seconds
[2025-03-27T16:43:55.376+0000] {processor.py:186} INFO - Started process (PID=5055) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:43:55.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:43:55.379+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:43:55.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:43:56.505+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:43:56.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 115, in <module>
    clear_data()
  File "/opt/airflow/dags/airflow_1.py", line 47, in clear_data
    df = df.drop('duration', axis=1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['duration'] not found in axis"
[2025-03-27T16:43:56.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:43:56.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.166 seconds
[2025-03-27T16:44:07.269+0000] {processor.py:186} INFO - Started process (PID=5101) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:07.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:44:07.271+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:44:07.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:08.468+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:44:08.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 88, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 58, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:44:08.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:08.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.248 seconds
[2025-03-27T16:44:38.820+0000] {processor.py:186} INFO - Started process (PID=5179) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:38.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:44:38.822+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:44:38.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:39.963+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:44:39.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 88, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 58, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:44:39.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:39.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.176 seconds
[2025-03-27T16:44:58.004+0000] {processor.py:186} INFO - Started process (PID=5218) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:58.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:44:58.006+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:44:58.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:59.073+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:44:59.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 88, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 58, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 36, in scale_frame
    X_scale = scaler.fit_transform(X.values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 918, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 894, in fit
    return self.partial_fit(X, y, sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_data.py", line 930, in partial_fit
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 2944, in validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1055, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 839, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'basic.4y'
[2025-03-27T16:44:59.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:44:59.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.106 seconds
[2025-03-27T16:45:17.591+0000] {processor.py:186} INFO - Started process (PID=5278) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:45:17.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:45:17.593+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:45:17.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:45:19.155+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:45:19.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 88, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 58, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 31, in scale_frame
    X = df.drop('y', axis=1)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['y'] not found in axis"
[2025-03-27T16:45:19.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:45:19.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.597 seconds
[2025-03-27T16:45:49.669+0000] {processor.py:186} INFO - Started process (PID=5353) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:45:49.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:45:49.671+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:45:49.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:45:51.247+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:45:51.242+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 88, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 58, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 31, in scale_frame
    X = df.drop('y', axis=1)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['y'] not found in axis"
[2025-03-27T16:45:51.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:45:51.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.611 seconds
[2025-03-27T16:46:21.914+0000] {processor.py:186} INFO - Started process (PID=5433) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:21.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:46:21.916+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:46:21.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:23.539+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:46:23.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 88, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 58, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 31, in scale_frame
    X = df.drop('y', axis=1)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['y'] not found in axis"
[2025-03-27T16:46:23.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:23.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.657 seconds
[2025-03-27T16:46:25.615+0000] {processor.py:186} INFO - Started process (PID=5454) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:25.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:46:25.617+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:46:25.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:27.220+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:46:27.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 89, in <module>
    train()
  File "/opt/airflow/dags/airflow_1.py", line 59, in train
    X,Y, power_trans = scale_frame(df)
                       ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_1.py", line 31, in scale_frame
    X = data.drop('target', axis=1)
        ^^^^
NameError: name 'data' is not defined
[2025-03-27T16:46:27.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:27.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.643 seconds
[2025-03-27T16:46:36.119+0000] {processor.py:186} INFO - Started process (PID=5494) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:36.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:46:36.122+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:46:36.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:40.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:46:40.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 4.676 seconds
[2025-03-27T16:47:27.574+0000] {processor.py:186} INFO - Started process (PID=5634) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:47:27.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:47:27.576+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:47:27.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:47:28.881+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:47:29.294+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:47:29.290+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:47:29.342+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:47:29.340+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:40:00+00:00, run_after=2025-03-27 16:45:00+00:00
[2025-03-27T16:47:29.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.989 seconds
[2025-03-27T16:47:59.739+0000] {processor.py:186} INFO - Started process (PID=5710) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:47:59.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:47:59.741+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:47:59.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:48:00.681+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:48:00.698+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:48:00.697+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T16:48:00.725+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:48:00.724+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 16:40:00+00:00, run_after=2025-03-27 16:45:00+00:00
[2025-03-27T16:48:00.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.020 seconds
[2025-03-27T16:48:48.579+0000] {processor.py:186} INFO - Started process (PID=5771) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T16:48:48.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T16:48:48.597+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:48:48.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:49:24.546+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:49:24.521+0000] {timeout.py:68} ERROR - Process timed out, PID: 5771
[2025-03-27T16:49:25.605+0000] {logging_mixin.py:190} INFO - [2025-03-27T16:49:25.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airflow_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_1.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from . import _joblib, metadata_routing
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_joblib.py", line 12, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/__init__.py", line 129, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 31, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/_parallel_backends.py", line 12, in <module>
    from ._utils import (
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/_utils.py", line 11, in <module>
    from .externals.loky.process_executor import _ExceptionWithTraceback
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/externals/loky/__init__.py", line 19, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/externals/loky/backend/reduction.py", line 77, in <module>
    from ._posix_reduction import _mk_inheritable  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1357, in _find_and_load
  File "<frozen importlib._bootstrap>", line 417, in __enter__
  File "<frozen importlib._bootstrap>", line 443, in _get_module_lock
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/airflow_1.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#reducing-dag-complexity, PID: 5771
[2025-03-27T16:49:25.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T16:49:25.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 37.280 seconds
[2025-03-27T17:05:22.633+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T17:05:22.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T17:05:22.640+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:22.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:05:23.955+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:05:24.081+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:24.081+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T17:05:24.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.812 seconds
[2025-03-27T17:05:32.573+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T17:05:32.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T17:05:32.576+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:32.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:05:33.177+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:05:33.191+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:33.190+0000] {taskinstance.py:3315} ERROR - {'DAG Id': 'train_pipelines', 'Task Id': 'train_some', 'Run Id': 'scheduled__2025-03-27T16:40:00+00:00', 'Hostname': 'cc9d85ccd39f', 'External Executor Id': '1f89020b-85f5-4377-b8e5-b31bec233518'}
[2025-03-27T17:05:33.503+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T17:05:33.503+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 16:48:21.931864+00:00 end:2025-03-27 17:05:33.196863+00:00 duration:1031.264999
[2025-03-27T17:05:33.504+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_some> dag:<DAG: train_pipelines> dagrun:<DagRun train_pipelines @ 2025-03-27 16:40:00+00:00: scheduled__2025-03-27T16:40:00+00:00, state:running, queued_at: 2025-03-27 16:48:09.587267+00:00. externally triggered: False>
[2025-03-27T17:05:33.504+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'train_pipelines', 'Task Id': 'train_some', 'Run Id': 'scheduled__2025-03-27T16:40:00+00:00', 'Hostname': 'cc9d85ccd39f', 'External Executor Id': '1f89020b-85f5-4377-b8e5-b31bec233518'}
[2025-03-27T17:05:33.505+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:33.505+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=train_pipelines, task_id=train_some, run_id=scheduled__2025-03-27T16:40:00+00:00, execution_date=20250327T164000, start_date=20250327T164821, end_date=20250327T170533
[2025-03-27T17:05:33.625+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:33.625+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: train_pipelines.train_some scheduled__2025-03-27T16:40:00+00:00 [failed]> in state failed
[2025-03-27T17:05:33.628+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:05:33.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T17:05:33.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.084 seconds
[2025-03-27T17:06:39.392+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T17:06:39.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T17:06:39.395+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:06:39.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:06:39.922+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:06:39.945+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:06:39.944+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T17:06:39.966+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:06:39.965+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 17:05:00+00:00, run_after=2025-03-27 17:10:00+00:00
[2025-03-27T17:06:39.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.597 seconds
[2025-03-27T17:07:10.589+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T17:07:10.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T17:07:10.592+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:07:10.592+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:07:11.315+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:07:11.334+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:07:11.333+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T17:07:11.542+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:07:11.541+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 17:05:00+00:00, run_after=2025-03-27 17:10:00+00:00
[2025-03-27T17:07:11.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.972 seconds
[2025-03-27T17:07:41.756+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T17:07:41.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T17:07:41.761+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:07:41.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:07:42.503+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:07:42.523+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:07:42.523+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T17:07:42.788+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:07:42.788+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 17:05:00+00:00, run_after=2025-03-27 17:10:00+00:00
[2025-03-27T17:07:42.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 1.058 seconds
[2025-03-27T17:08:12.858+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/airflow_1.py
[2025-03-27T17:08:12.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airflow_1.py for tasks to queue
[2025-03-27T17:08:12.861+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:08:12.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:08:13.396+0000] {processor.py:925} INFO - DAG(s) 'train_pipelines' retrieved from /opt/airflow/dags/airflow_1.py
[2025-03-27T17:08:13.413+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:08:13.412+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-27T17:08:13.605+0000] {logging_mixin.py:190} INFO - [2025-03-27T17:08:13.605+0000] {dag.py:4180} INFO - Setting next_dagrun for train_pipelines to 2025-03-27 17:05:00+00:00, run_after=2025-03-27 17:10:00+00:00
[2025-03-27T17:08:13.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airflow_1.py took 0.765 seconds
